Repository BeeLinkers/EngleBee, pull requests merged in 2024-08, with the labels that each got.

#6 [feat-jpa-setting] JPA 엔티티 생성을 위한 Builder 추가 및, Enum값 반환 메서드 추가, 연관관계 편의 메서드 & 엔티티 상태 변화 메서드 추가
  src/main/java/com/beelinkers/englebee/admin/domain/entity/CallLLMLog.java
  src/main/java/com/beelinkers/englebee/admin/domain/entity/CreatedLectureLog.java
  src/main/java/com/beelinkers/englebee/auth/domain/entity/Member.java
  src/main/java/com/beelinkers/englebee/auth/domain/entity/StudentGrade.java
  src/main/java/com/beelinkers/englebee/auth/exception/InvalidStudentGradeException.java
  src/main/java/com/beelinkers/englebee/auth/exception/TempAuthCustomerException.java
  src/main/java/com/beelinkers/englebee/auth/exception/handler/AuthDomainEnumExceptionHandler.java
  src/main/java/com/beelinkers/englebee/auth/exception/handler/TempAuthExceptionHandler.java
  src/main/java/com/beelinkers/englebee/common/BaseEntity.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/Exam.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/Lecture.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/LectureSubjectLevel.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/LevelCode.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/MemberSubjectLevel.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/Question.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/Reply.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/SubjectCode.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/SubjectLevel.java
  src/main/java/com/beelinkers/englebee/general/exception/InvalidLevelCodeException.java
  src/main/java/com/beelinkers/englebee/general/exception/InvalidSubjectCodeException.java
  src/main/java/com/beelinkers/englebee/general/exception/TempGeneralCustomerException.java
  src/main/java/com/beelinkers/englebee/general/exception/handler/GeneralDomainEnumExceptionHandler.java
  src/main/java/com/beelinkers/englebee/general/exception/handler/TempGeneralExceptionHandler.java
  src/main/java/com/beelinkers/englebee/teacher/domain/entity/TeacherQuestion.java
  src/test/java/com/beelinkers/englebee/auth/domain/entity/MemberTest.java
Labels: 📄 설정, ✨ 기능개발, 🌟 리팩토링

#11 [4-feat-general-videochat-socket] 소켓, WebRTC를 활용한 화상회의 구현
  build.gradle
  src/main/java/com/beelinkers/englebee/general/controller/page/ChatController.java
  src/main/java/com/beelinkers/englebee/general/videochat/MyWebSocketHandler.java
  src/main/java/com/beelinkers/englebee/global/WebMvcConfig.java
  src/main/java/com/beelinkers/englebee/global/WebSocketConfig.java
  src/main/resources/templates/general/socket.html
  src/main/resources/templates/general/webrtc.html
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, 💼 의존성, 📄 설정, ✨ 기능개발

#12 [feat-teacher-main-api] 선생님 메인 페이지 API 구현
  src/main/java/com/beelinkers/englebee/general/domain/repository/ExamRepository.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/LectureRepository.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentMainServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherMainApiController.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMainPageAuthoredExamDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMainPageLectureDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMainPageNewExamDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMainPageQuestionDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherMainPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/service/TeacherMainService.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherMainServiceImpl.java
  src/test/java/com/beelinkers/englebee/teacher/controller/api/TeacherMainApiControllerTest.java
  src/test/java/com/beelinkers/englebee/teacher/service/impl/TeacherMainServiceImplTest.java
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#15 [feat-infra-cicd-setting] 배포 환경 구축 및 CI/CD 파이프라인을 통한 자동 배포 설정
  .dockerignore
  .github/workflows/cicd.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/beelinkers/englebee/DBConnectionTestController.java
  src/main/java/com/beelinkers/englebee/HelloController.java
  src/main/java/com/beelinkers/englebee/auth/domain/entity/Member.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/test/java/com/beelinkers/englebee/EngleBeeApplicationTests.java
  src/test/java/com/beelinkers/englebee/auth/domain/repository/MemberRepositoryTest.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: 💼 의존성, 📄 설정, ☁ 배포/인프라, ✨ 기능개발

#16 [feat-student-main-api] 학생 메인 페이지 코드 수정 및 Test Code 작성
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentMainApiController.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageLectureDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageNewExamDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageQuestionDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageSubmitExamDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/StudentMainPageMapper.java
  src/main/java/com/beelinkers/englebee/student/service/StudentMainService.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentMainServiceImpl.java
  src/test/java/com/beelinkers/englebee/student/controller/api/StudentMainApiControllerTest.java
  src/test/java/com/beelinkers/englebee/student/service/impl/StudentMainServiceImplTest.java
Labels: 🧑‍🎓 학생, ✨ 기능개발

#22 [feat-student-mypage-api] 학생 마이 페이지 API 구현
  src/main/java/com/beelinkers/englebee/general/domain/repository/QuestionRepository.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/ReplyRepository.java
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentMyApiController.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMyPageCompletedExamDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMyPageCreatedExamDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMyPageWrittenQnaDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMyPageWrittenReplyDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/StudentMyPageMapper.java
  src/main/java/com/beelinkers/englebee/student/service/StudentMyService.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentMyServiceImpl.java
Labels: 🧑‍🎓 학생, ✨ 기능개발

#23 [feat-auth-oauth2-google-login-session-api] 스프링 시큐리티와 OAuth2를 이용한 구글/네이버 로그인 구현, 추가회원가입/로그아웃/회원탈퇴 기능 구현, 테스트 코드 및 테스트 데이터 수정
  .github/workflows/cicd.yml
  .gitignore
  src/main/java/com/beelinkers/englebee/EngleBeeApplication.java
  src/main/java/com/beelinkers/englebee/auth/annotation/LoginMember.java
  src/main/java/com/beelinkers/englebee/auth/annotation/SignupProgressMember.java
  src/main/java/com/beelinkers/englebee/auth/argumentresolver/LoginMemberArgumentResolver.java
  src/main/java/com/beelinkers/englebee/auth/argumentresolver/SignupProgressMemberArgumentResolver.java
  src/main/java/com/beelinkers/englebee/auth/config/SecurityConfig.java
  src/main/java/com/beelinkers/englebee/auth/config/WebConfig.java
  src/main/java/com/beelinkers/englebee/auth/constant/AuthConstant.java
  src/main/java/com/beelinkers/englebee/auth/controller/api/AuthApiController.java
  src/main/java/com/beelinkers/englebee/auth/controller/page/AuthPageController.java
  src/main/java/com/beelinkers/englebee/auth/domain/entity/LoginType.java
  src/main/java/com/beelinkers/englebee/auth/domain/entity/Member.java
  src/main/java/com/beelinkers/englebee/auth/domain/repository/MemberRepository.java
  src/main/java/com/beelinkers/englebee/auth/dto/request/StudentSignupRequestDTO.java
  src/main/java/com/beelinkers/englebee/auth/dto/request/TeacherSignupRequestDTO.java
  src/main/java/com/beelinkers/englebee/auth/dto/request/TempAuthRequestDTO.java
  src/main/java/com/beelinkers/englebee/auth/dto/request/mapper/TempMapper.java
  src/main/java/com/beelinkers/englebee/auth/dto/response/TempAuthResponseDTO.java
  src/main/java/com/beelinkers/englebee/auth/dto/response/mapper/TempMapper.java
  src/main/java/com/beelinkers/englebee/auth/exception/InvalidLoginTypeException.java
  src/main/java/com/beelinkers/englebee/auth/exception/SignupProgressSessionNotFoundException.java
  src/main/java/com/beelinkers/englebee/auth/exception/handler/AuthDomainEnumExceptionHandler.java
  src/main/java/com/beelinkers/englebee/auth/exception/handler/AuthDomainInputExceptionHandler.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/AlreadySignedUpEmailException.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/SignupRequiredException.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/UnsupportedSocialLoginTypeException.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/session/SessionMember.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/session/SignupProgressSessionMember.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/CustomOAuth2User.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/CustomOAuth2UserService.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/GoogleResponse.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/NaverResponse.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/OAuth2Response.java
  src/main/java/com/beelinkers/englebee/auth/service/AuthService.java
  src/main/java/com/beelinkers/englebee/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/beelinkers/englebee/general/controller/api/MemberApiController.java
  src/main/java/com/beelinkers/englebee/general/controller/page/MainPageController.java
  src/main/java/com/beelinkers/englebee/general/controller/page/SignupProgressPageController.java
  src/main/java/com/beelinkers/englebee/general/exception/MemberNicknameDuplicatedException.java
  src/main/java/com/beelinkers/englebee/general/exception/MemberNicknameLengthException.java
  src/main/java/com/beelinkers/englebee/general/exception/MemberNotFoundException.java
  src/main/java/com/beelinkers/englebee/general/exception/handler/GeneralDomainInputExceptionHandler.java
  src/main/java/com/beelinkers/englebee/general/service/GeneralMemberService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/GeneralMemberServiceImpl.java
  src/main/java/com/beelinkers/englebee/global/GlobalTempConfig.java
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/auth/signup-progress.html
  src/main/resources/templates/common-main.html
  src/test/java/com/beelinkers/englebee/auth/domain/entity/MemberTest.java
  src/test/java/com/beelinkers/englebee/student/controller/api/StudentMainApiControllerTest.java
  src/test/java/com/beelinkers/englebee/teacher/controller/api/TeacherMainApiControllerTest.java
  src/test/resources/application.properties
  src/test/resources/schema.sql
Labels: 🔑 인증/인가, 💼 의존성, 📄 설정, ☁ 배포/인프라, 🐛 버그수정, ✨ 기능개발

#26 [feat-infra-session-db-setting]
  build.gradle
Labels: 🔑 인증/인가, 💼 의존성, ☁ 배포/인프라

#27 [feat-teacher-mypage-api] 선생님 마이페이지 API 구현
  src/main/java/com/beelinkers/englebee/general/domain/repository/ReplyRepository.java
  src/main/java/com/beelinkers/englebee/student/dto/response/TempStudentResponseDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/TempMapper.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentMyServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherMyApiController.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMyPageExamHistoryDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMyPagePendingExamDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMyPageWrittenQnaDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMyPageWrittenReplyDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TempTeacherResponseDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherMyPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TempMapper.java
  src/main/java/com/beelinkers/englebee/teacher/service/TeacherMyService.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherMyServiceImpl.java
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#28 [feat-admin-dashboard-all] 관리자 대쉬보드 구현
  src/main/java/com/beelinkers/englebee/admin/controller/api/AdminApiController.java
  src/main/java/com/beelinkers/englebee/admin/domain/repository/CallLLMLogRepository.java
  src/main/java/com/beelinkers/englebee/admin/domain/repository/CreatedLectureLogRepository.java
  src/main/java/com/beelinkers/englebee/admin/dto/request/AdminYearMonthDTO.java
  src/main/java/com/beelinkers/englebee/admin/dto/response/AdminDashboardDayGroupCountDTO.java
  src/main/java/com/beelinkers/englebee/admin/dto/response/AdminDashboardMemberChartDTO.java
  src/main/java/com/beelinkers/englebee/admin/dto/response/AdminMemberAgeGroupCountDTO.java
  src/main/java/com/beelinkers/englebee/admin/dto/response/AdminMemberSubjectLevelCountDTO.java
  src/main/java/com/beelinkers/englebee/admin/service/AdminService.java
  src/main/java/com/beelinkers/englebee/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/beelinkers/englebee/auth/domain/repository/MemberRepository.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/MemberSubjectLevelRepository.java
  src/main/resources/static/assets/css/hr.css
  src/main/resources/static/assets/js/admin-chart.js
  src/main/resources/templates/admin/admin-dashboard.html
Labels: 🧑‍💻 관리자, ✨ 기능개발
