Repository BeeLinkers/EngleBee, pull requests merged in 2024-09, with the labels that each got.

#32 [refactor-student-main-api] 학생 메인 페이지 api 코드 수정 및 Test Code 구현
  src/main/java/com/beelinkers/englebee/general/domain/repository/ExamRepository.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/LectureRepository.java
  src/main/java/com/beelinkers/englebee/general/dto/response/SubjectLevelCodeDTO.java
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentMainApiController.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageLectureDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/StudentMainPageMapper.java
  src/main/java/com/beelinkers/englebee/student/service/StudentMainService.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentMainServiceImpl.java
  src/test/java/com/beelinkers/englebee/student/controller/api/StudentMainApiControllerTest.java
  src/test/java/com/beelinkers/englebee/student/service/impl/StudentMainServiceImplTest.java
Labels: 🧑‍🎓 학생, 🌟 리팩토링

#37 [refactor-general-videochat-api] 수업 종료 이벤트 구현 및 배포 환경에 맞춘 시그널링 서버 주소 수정
  src/main/java/com/beelinkers/englebee/general/controller/api/ChatApiController.java
  src/main/java/com/beelinkers/englebee/general/controller/page/ChatController.java
  src/main/java/com/beelinkers/englebee/general/exception/InvalidLectureSeqException.java
  src/main/java/com/beelinkers/englebee/general/exception/handler/GeneralDomainSeqExceptionHandler.java
  src/main/java/com/beelinkers/englebee/general/service/ChatService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/ChatServiceImpl.java
  src/main/java/com/beelinkers/englebee/global/WebMvcConfig.java
  src/main/resources/templates/general/webrtc.html
  src/test/java/com/beelinkers/englebee/general/service/ChatServiceImplTest.java
Labels: ✨ 기능개발, 🌟 리팩토링

#39 [hotfix-general-videochat-test] 수업 종료 서비스 테스트 코드 수정
  src/test/java/com/beelinkers/englebee/general/service/ChatServiceImplTest.java
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, 🐛 버그수정

#42 [refactor-general-admin-test] 화상채팅/관리자 테스트 코드
  src/test/java/com/beelinkers/englebee/admin/controller/api/AdminApiControllerTest.java
  src/test/java/com/beelinkers/englebee/admin/service/impl/AdminServiceImplTest.java
  src/test/java/com/beelinkers/englebee/general/controller/api/ChatApiControllerTest.java
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, 🧑‍💻 관리자, 🌟 리팩토링

#45 [fix-teacher-exam-register-and-feedback] 선생님 시험 등록 페이지, 시험 피드백 페이지에 학생의 학년을 model에 반환하는 기능 추가
  src/main/java/com/beelinkers/englebee/teacher/controller/page/TeacherExamPageController.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherExamFeedbackPageDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherExamRegisterPageDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherExamFeedbackPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherExamRegisterPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherExamPageServiceImpl.java
Labels: 🧑‍🏫 선생님, 🐛 버그수정

#47 [feat-student-account-all] 학생 계정 페이지 api 구현 및 공통 Account Page Controller 및 service 구현
  src/main/java/com/beelinkers/englebee/auth/domain/entity/Member.java
  src/main/java/com/beelinkers/englebee/general/controller/page/AccountPageController.java
  src/main/java/com/beelinkers/englebee/general/service/AccountService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/AccountServiceImpl.java
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentAccountApiController.java
  src/main/java/com/beelinkers/englebee/student/dto/request/StudentAccountPageRequestDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentAccountPageResponseDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/StudentAccountPageMapper.java
  src/main/java/com/beelinkers/englebee/student/service/StudentAccountService.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentAccountServiceImpl.java
  src/main/resources/templates/student/student-account.html
  src/main/resources/templates/student/student-mypage-account.html
Labels: 🧑‍🎓 학생, ✨ 기능개발

#50 [feat-teacher-account-all] 선생님 계정 페이지 api 구현
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentAccountServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherAccountApiController.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherAccountPageRequestDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherAccountPageResponseDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherAccountUpdateDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherInfoDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherAccountPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherInfoMapper.java
  src/main/java/com/beelinkers/englebee/teacher/service/TeacherAccountService.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherAccountServiceImpl.java
  src/main/resources/templates/teacher/teacher-account.html
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#48 [feat-teacher-lecture-api] 메인 페이지에서 수업 등록하는 api 생성
  src/main/java/com/beelinkers/englebee/general/controller/page/ChatController.java
  src/main/java/com/beelinkers/englebee/general/service/LectureService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/LectureServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherLectureApiController.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherRegisterLectureRequestDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherRegisterLectureSubjectLevelDTO.java
  src/main/resources/templates/general/webrtc.html
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#53 [hotfix-general-videochat] 화상채팅관련 코드 수정
  src/main/java/com/beelinkers/englebee/general/controller/page/ChatController.java
  src/main/resources/templates/general/webrtc.html
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, 🐛 버그수정

#55 [feat-general-qna-api] Q&A 리스트 페이지 및 새 글 등록 페이지, 상세 페이지(댓글 등록 및 조회) 기능 api 구현
  src/main/java/com/beelinkers/englebee/general/controller/api/QnaApiController.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/QuestionRepository.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/ReplyRepository.java
  src/main/java/com/beelinkers/englebee/general/dto/request/QnaPageRequestDTO.java
  src/main/java/com/beelinkers/englebee/general/dto/request/ReplyRequestDTO.java
  src/main/java/com/beelinkers/englebee/general/dto/request/mapper/QnaPageRequestMapper.java
  src/main/java/com/beelinkers/englebee/general/dto/request/mapper/ReplyRequestMapper.java
  src/main/java/com/beelinkers/englebee/general/dto/response/QnaDetailPageResponseDTO.java
  src/main/java/com/beelinkers/englebee/general/dto/response/QnaPageResponseDTO.java
  src/main/java/com/beelinkers/englebee/general/dto/response/ReplyResponseDTO.java
  src/main/java/com/beelinkers/englebee/general/dto/response/mapper/QnaDetailPageResponseMapper.java
  src/main/java/com/beelinkers/englebee/general/dto/response/mapper/QnaPageResponseMapper.java
  src/main/java/com/beelinkers/englebee/general/dto/response/mapper/ReplyResponseMapper.java
  src/main/java/com/beelinkers/englebee/general/service/QnaService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/QnaServiceImpl.java
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, ✨ 기능개발

#58 [feat-auth-oauth2-signup-in-production-all] 네이버,구글 회원가입/로그인, 추가회원가입, 로그아웃, 회원탈퇴 API와 뷰 연동 | 인증, 인가 관련 뷰 수정
  src/main/java/com/beelinkers/englebee/auth/config/SecurityConfig.java
  src/main/java/com/beelinkers/englebee/auth/controller/api/AuthApiController.java
  src/main/java/com/beelinkers/englebee/auth/controller/page/SignupProgressPageController.java
  src/main/java/com/beelinkers/englebee/auth/dto/request/NicknameCheckRequestDTO.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/DeactivatedMemberException.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/exception/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/session/SessionMember.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/session/SignupProgressSessionMember.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/CustomOAuth2UserService.java
  src/main/java/com/beelinkers/englebee/auth/oauth2/userinfo/GoogleResponse.java
  src/main/java/com/beelinkers/englebee/auth/service/AuthService.java
  src/main/java/com/beelinkers/englebee/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/beelinkers/englebee/general/controller/api/MemberApiController.java
  src/main/java/com/beelinkers/englebee/general/controller/page/MainPageController.java
  src/main/java/com/beelinkers/englebee/general/domain/entity/LevelCode.java
  src/main/java/com/beelinkers/englebee/general/service/GeneralMemberService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/GeneralMemberServiceImpl.java
  src/main/java/com/beelinkers/englebee/global/GlobalExceptionHandler.java
  src/main/java/com/beelinkers/englebee/global/GlobalTempConstant.java
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentAccountApiController.java
  src/main/java/com/beelinkers/englebee/student/service/StudentAccountService.java
  src/main/java/com/beelinkers/englebee/student/service/impl/StudentAccountServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherAccountApiController.java
  src/main/java/com/beelinkers/englebee/teacher/service/TeacherAccountService.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherAccountServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/templates/auth/signup-progress.html
  src/main/resources/templates/fragments/top-nav-without-menu.html
  src/main/resources/templates/fragments/top-nav.html
  src/main/resources/templates/general/exam-detail.html
  src/main/resources/templates/student/student-main.html
Labels: 🔑 인증/인가, 🐛 버그수정, ✨ 기능개발, 🌟 리팩토링

#62 [feat-general-qna-view] Q&A 리스트 페이지, 새 글 등록 페이지, 상세페이지 & 댓글 조회 및 댓글 등록 기능 구현
  src/main/java/com/beelinkers/englebee/general/controller/page/QnaPageController.java
  src/main/resources/templates/qna/qna-detail.html
  src/main/resources/templates/qna/qna-list.html
  src/main/resources/templates/qna/qna-register.html
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, ✨ 기능개발

#66 [feat-general-lecture-all] 선생님 메인 페이지에서 수업 등록 구현
  src/main/java/com/beelinkers/englebee/general/exception/NoSubjectLevelException.java
  src/main/java/com/beelinkers/englebee/general/exception/handler/GeneralDomainInputExceptionHandler.java
  src/main/java/com/beelinkers/englebee/general/service/impl/LectureServiceImpl.java
  src/main/resources/static/js/register-lecture.js
  src/main/resources/templates/admin/admin-dashboard.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/teacher/teacher-main.html
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#68 [feat-teacher-exam-recommendation-api] 시험 등록 페이지 API - 뷰 연동 ( 시험 등록 API + GPT에게 문제 추천 API )
  .github/workflows/cicd.yml
  build.gradle
  src/main/java/com/beelinkers/englebee/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/beelinkers/englebee/general/controller/page/ExamDetailPageController.java
  src/main/java/com/beelinkers/englebee/general/service/GeneralExamService.java
  src/main/java/com/beelinkers/englebee/general/service/GeneralMemberService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/GeneralExamServiceImpl.java
  src/main/java/com/beelinkers/englebee/general/service/impl/GeneralExamValidationServiceImpl.java
  src/main/java/com/beelinkers/englebee/general/service/impl/GeneralMemberServiceImpl.java
  src/main/java/com/beelinkers/englebee/global/GptAsyncConfig.java
  src/main/java/com/beelinkers/englebee/global/GptConfig.java
  src/main/java/com/beelinkers/englebee/student/exception/StudentIllegalAccessToExamException.java
  src/main/java/com/beelinkers/englebee/student/exception/TempStudentCustomerException.java
  src/main/java/com/beelinkers/englebee/student/exception/handler/StudentDomainInputExceptionHandler.java
  src/main/java/com/beelinkers/englebee/student/exception/handler/TempStudentExceptionHandler.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherExamApiController.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherGPTApiController.java
  src/main/java/com/beelinkers/englebee/teacher/controller/page/TeacherExamPageController.java
  src/main/java/com/beelinkers/englebee/teacher/domain/entity/TeacherQuestion.java
  src/main/java/com/beelinkers/englebee/teacher/domain/repository/TeacherQuestionRepository.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherExamRegisterRequestDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherQuestionCreateRequestDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherExamRegisterPageDTO.java
  src/main/java/com/beelinkers/englebee/teacher/exception/SubjectLevelNotFoundException.java
  src/main/java/com/beelinkers/englebee/teacher/exception/handler/TeacherDomainInputExceptionHandler.java
  src/main/java/com/beelinkers/englebee/teacher/llm/GptChatCompletionRequest.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptApiController.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptConstant.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptProxy.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptProxyImpl.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptService.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptUtil.java
  src/main/java/com/beelinkers/englebee/teacher/service/TeacherGPTService.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherGPTServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/assets-old/img/.DS_Store
  src/main/resources/static/assets-old/img/logo/.DS_Store
  src/main/resources/templates/teacher/exam-register.html
  src/test/resources/application.properties
Labels: 🧑‍🏫 선생님, 💼 의존성, 📄 설정, ✨ 기능개발

#70 [feat-admin-dashboard-api] 수업 생성, LLM API 호출 로그기록 AOP 구현
  src/main/java/com/beelinkers/englebee/admin/aspect/CallLLMLogAspect.java
  src/main/java/com/beelinkers/englebee/admin/aspect/LectureCreationLogAspect.java
  src/main/resources/templates/admin/admin-dashboard.html
  src/main/resources/templates/fragments/admin-scripts.html
Labels: 🧑‍💻 관리자, ✨ 기능개발

#71 [feat-student-my-view] 학생 my 페이지에서 내가 작성한 게시글 리스트 조회 기능 구현
  src/main/java/com/beelinkers/englebee/general/controller/page/MyPageController.java
  src/main/java/com/beelinkers/englebee/general/service/MyPageService.java
  src/main/java/com/beelinkers/englebee/general/service/impl/MyPageServiceImpl.java
  src/main/resources/templates/student/student-info.html
Labels: 🧑‍🎓 학생, ✨ 기능개발

#74 [feat-teacher-my-view] 선생님 my 페이지에서 내가 작성한 게시글 리스트 조회 기능 구현
  src/main/java/com/beelinkers/englebee/general/controller/page/MyPageController.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherMyServiceImpl.java
  src/main/resources/templates/student/student-info.html
  src/main/resources/templates/teacher/teacher-info.html
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#76 [feat-exam-teacher-feedback-page-all] 선생님 시험 피드백 페이지 구현 완료 ( 시험 피드백 확인 + GPT에게 피드백 추천받기 + 학생 레벨 평가 )
  src/main/java/com/beelinkers/englebee/general/domain/entity/Exam.java
  src/main/java/com/beelinkers/englebee/teacher/controller/page/TeacherExamPageController.java
  src/main/java/com/beelinkers/englebee/teacher/domain/repository/TeacherQuestionRepository.java
  src/main/java/com/beelinkers/englebee/teacher/dto/request/TeacherExamFeedbackRequestDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherExamFeedbackPageDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherQuestionForTeacherToFeedbackDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherExamFeedbackPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptApiController.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptConstant.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptProxy.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptProxyImpl.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptService.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptServiceImpl.java
  src/main/java/com/beelinkers/englebee/teacher/llm/TeacherGptUtil.java
  src/main/java/com/beelinkers/englebee/teacher/service/impl/TeacherExamPageServiceImpl.java
  src/main/resources/templates/teacher/exam-feedback.html
  src/main/resources/templates/teacher/exam-register.html
Labels: 🧑‍🏫 선생님, ✨ 기능개발

#78 [feat-qna-llm-auto-reply-api] 질문 등록 시 GPT의 자동 댓글 생성 구현체 작성 완료
  src/main/java/com/beelinkers/englebee/general/controller/page/ExamDetailPageController.java
  src/main/java/com/beelinkers/englebee/general/llm/GeneralGptConstant.java
  src/main/java/com/beelinkers/englebee/general/llm/GeneralGptTestController.java
  src/main/java/com/beelinkers/englebee/general/llm/GeneralGptUtil.java
  src/main/java/com/beelinkers/englebee/general/llm/GptQnaProxy.java
  src/main/java/com/beelinkers/englebee/general/llm/GptQnaProxyImpl.java
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, ✨ 기능개발

#79 [feat-student-exam-view] 학생 문제 풀기 페이지 구현
  src/main/java/com/beelinkers/englebee/admin/aspect/CallLLMLogAspect.java
  src/main/resources/static/js/register-lecture.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/student/exam-solve.html
Labels: 🧑‍🎓 학생, ✨ 기능개발

#80 [llm-auto-make-reply-to-question] Q&A 작성 시, 자동으로 GPT가 첫번째 댓글 달아주는 기능 구현 | ObjectMapper 빈 관련 설정 수정 | 질문 등록 페이지 뷰 구현
  src/main/java/com/beelinkers/englebee/general/llm/GeneralGptConstant.java
  src/main/java/com/beelinkers/englebee/general/service/impl/QnaServiceImpl.java
  src/main/java/com/beelinkers/englebee/global/GptConfig.java
  src/main/resources/templates/qna/qna-detail.html
  src/main/resources/templates/qna/qna-register.html
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, 📄 설정, 🐛 버그수정, ✨ 기능개발

#82 [feat-general-my-view] 선생님/학생 계정 페이지 구현
  src/main/java/com/beelinkers/englebee/general/controller/page/AccountPageController.java
  src/main/java/com/beelinkers/englebee/student/controller/api/StudentAccountApiController.java
  src/main/java/com/beelinkers/englebee/teacher/controller/api/TeacherAccountApiController.java
  src/main/resources/templates/fragments/top-nav.html
  src/main/resources/templates/student/student-account.html
  src/main/resources/templates/teacher/teacher-account.html
Labels: 🧑‍🎓 학생, 🧑‍🏫 선생님, ✨ 기능개발

#83 [feat-student-main-view] 학생 메인 페이지 구현
  src/main/java/com/beelinkers/englebee/general/controller/page/MainPageController.java
  src/main/java/com/beelinkers/englebee/general/domain/repository/LectureRepository.java
  src/main/java/com/beelinkers/englebee/student/dto/response/StudentMainPageLectureDTO.java
  src/main/java/com/beelinkers/englebee/student/dto/response/mapper/StudentMainPageMapper.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/TeacherMainPageLectureDTO.java
  src/main/java/com/beelinkers/englebee/teacher/dto/response/mapper/TeacherMainPageMapper.java
  src/main/resources/templates/student/student-main.html
Labels: 🧑‍🎓 학생, ✨ 기능개발
